{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fynncloud.fullname" . }}-redis
  labels:
    {{- include "fynncloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "fynncloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
